### ISSUE TITLE
Command line version

### ISSUE THREAD

**Issue by rjkantor** [rabbitvcs/rabbitvcs#106]
Switch command appears to not work I get a trace back and unknown key message.  Is this a known issue in v .16?

**Comment by axel-h** [comment]
Error still exists:

$ rabbitvcs changes
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/changes.py", line 594, in <module>
    window = changes_factory(options.vcs, pathrev1[0], pathrev1[1], pathrev2[0], pathrev2[1])
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/changes.py", line 580, in changes_factory
    return classes_map[vcs](path1, revision1, path2, revision2)
KeyError: 'unknown'

**Comment by rootkit7628** [comment]
I've got same error when trying to use branch command of svn :
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/branch.py", line 153, in <module>
    window = branch_factory(options.vcs, args[0], options.revision)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/branch.py", line 143, in branch_factory
    return classes_map[vcs](path, revision)
KeyError: 'unknown'
```
