### ISSUE TITLE
100% cpu on centos6.6 with git

### ISSUE THREAD

**Issue by styrmani** [rabbitvcs/rabbitvcs#113]
After started using git (just with SmartGIT) Nautilus starts to run wild 100% and becomes unresponsive. 

Seems to work ok with just until using nautilus to navigate to one of the git directories on local filesystem. After that at some point the problem begins.

I believe its rabbitvcs nautilus integration that causes this, since uninstalling rabbit fixes the problem.

Would it be possible as a quick fix to get an option e.g. to disable the git functionality?

**Comment by gunterkoenigsmann** [comment]
I can bet if you do a

      killall nautilus
      nautilus .

from the command line the output you will see will be:

```
None
ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
    path_dict = self.status_checker.generate_menu_conditions(upaths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 55, in generate_menu_conditions
    conditions = MainContextMenuConditions(self.vcs_client, paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1207, in __init__
    self.generate_statuses(paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1217, in generate_statuses
    statuses_tmp = self.vcs_client.statuses(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 210, in statuses
    client = self.client(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 189, in client
    return self.git(guess["repo_path"], is_repo_path=False)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 117, in git
    repo_path = git.find_repository_path(path)
AttributeError: Dummy instance has no attribute 'find_repository_path'
```

**Comment by styrmani** [comment]
Thanks for the help. I'm not sure if debug settings are required, but
nothing was printed to console after the commands.

On /var/log/messages i have:

Jun 21 18:21:26 localhost abrt: detected unhandled Python exception in
'nautilus'
