### ISSUE TITLE
Thunar plugin not working

### ISSUE THREAD

**Issue by michael-heyns** [rabbitvcs/rabbitvcs#145]
Thunar terminal output shows:
```
Traceback (most recent call last):
  File "/usr/lib/thunarx-2/python/RabbitVCS.py", line 41, in <module>
    from rabbitvcs.vcs.svn import SVN
  File "/usr/lib/python2.7/site-packages/rabbitvcs/vcs/svn/__init__.py", line 49, in <module>
    class Revision:
  File "/usr/lib/python2.7/site-packages/rabbitvcs/vcs/svn/__init__.py", line 56, in Revision
    "unspecified":      pysvn.opt_revision_kind.unspecified,
AttributeError: 'opt_revision_kind' object has no attribute 'unspecified'
```

Unfortunately no rabbitvcs.log output, even with debug level.

RabbitVCS 0.16, Thunar 1.6.10

**Comment by adamplumb** [comment]
Can you try installing RabbitVCS master?  It is working for me.

**Comment by jristz** [comment]
Well now thunar 1.8.0 resentfully release requires newer python-xthunar which is python3

So more work pile up for a migration to python 3

**Comment by JotaRandom** [comment]
Well now xfce 4.14 has been released and it use Thunar gtk3...

I dont want to be harsh bringing this up but now is the moment to post python3 and gtk3 or just deprecated the plugin for lack of coders and maintainers
