### ISSUE TITLE
Bomb Symbol for git folder in linux mint 17.3 (neon)

### ISSUE THREAD

**Issue by ULTIMATEUPGRADE** [rabbitvcs/rabbitvcs#148]
Trace back of rabbitvcs.log
2016-04-06 10:55:27,153 ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
    path_dict = self.status_checker.generate_menu_conditions(upaths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 55, in generate_menu_conditions
    conditions = MainContextMenuConditions(self.vcs_client, paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1193, in __init__
    self.generate_statuses(paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1203, in generate_statuses
    statuses_tmp = self.vcs_client.statuses(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 183, in statuses
    return client.statuses(path, recurse=recurse, invalidate=invalidate)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/__init__.py", line 173, in statuses
    gittyup_statuses = self.client.status(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1356, in status
    return self.status_porcelain(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1198, in status_porcelain
    untracked_path = components.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
None

**Comment by adamplumb** [comment]
Huh that's interesting.  Someone else reported this same stacktrace recently.  What version of rabbitvcs are you using?
