### ISSUE TITLE
AttributeError: When using gi.repository you must not import static modules like "gobject"

### ISSUE THREAD

**Issue by justpusher** [rabbitvcs/rabbitvcs#173]
This error is flooding my /home/xxx/.config/rabbitvcs/RabbitVCS.log and eating my free space. The log is already 2.3GB. 
By the way, .config is not a good place for large logs. Consider ~/.local/share
RabbitVCS 0.16.0

```
None
2016-11-10 13:40:07,306 ERROR   rabbitvcs.services.checkerservice       org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
    path_dict = self.status_checker.generate_menu_conditions(upaths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 53, in generate_menu_conditions
    from rabbitvcs.util.contextmenu import MainContextMenuConditions
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 45, in <module>
    from contextmenuitems import *
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenuitems.py", line 381, in <module>
    class MenuRepoBrowser(MenuItem):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenuitems.py", line 385, in MenuRepoBrowser
    icon = gtk.STOCK_FIND
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 64, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

```

**Comment by gilder0** [comment]
Try my fix for this : 
https://github.com/rabbitvcs/rabbitvcs/pull/189

**Comment by adamplumb** [comment]
This should be changed on master now.  Thanks for the PR!
