### ISSUE TITLE
apply patch failing for added files

### ISSUE THREAD

**Issue by luma7** [rabbitvcs/rabbitvcs#176]
Hi,
I'm using RabbitVCS with Nautilus integration in Ubuntu 16.04 LTS.

Here the content of /home/martin/Patches/test.patch, generated with RabbitVCS:

```
Index: test.txt
===================================================================
--- test.txt	(nicht existent)
+++ test.txt	(Arbeitskopie)
@@ -0,0 +1 @@
+Lorem ipsum dolor sit amet, nusquam disputationi ius an. Te tale aperiam tamquam pri, dico veritus in sit. Vis no reque omnium admodum. Mei detracto concludaturque et, ea duis elaboraret vim. Erat nihil eligendi ut pri.
```

Then in /home/martin/code: right-klick -> RabbitVCS SVN -> Apply Patch... -> select /home/martin/Patches/test.patch
produces:
add() got an unexpected keyword argument 'depth'

It also fails in the console:

martin@myhost:~/code$ svn patch '/home/martin/Patches/test.patch' 
Fehlendes Ziel: »test.txt« übersprungen
Konfliktübersicht:
  Übersprungene Pfade: 1

What can I do?

RabbitVCS 0.16.0
Subversion - 1.9.3.
Pysvn - 1.8.0.0
ConfigObj - 5.0.6
Ubuntu 16.04 LTS

Martin

**Comment by adamplumb** [comment]
Do you have the full stack trace of the error you got when applying the patch?  I'm unable to reproduce this on master.

**Comment by martin-luy** [comment]
Now "svn patch" is working in the console, but I still get the error with Nautilus and RabbitVCS, see the screenshot below.

![bildschirmfoto vom 2017-06-21 23-38-22](https://user-images.githubusercontent.com/4472985/27407989-ee51b108-56da-11e7-8e48-f262223373a5.png)

I only get that message from the graphical interface. Could you tell me the steps to get the stack trace?

The file was generated in the destination folder, but it's not in 'added' status, so probably some automatic "svn add" failed.

**Comment by adamplumb** [comment]
You might be getting logs in ~/.config/rabbitvcs. If not check the log tab
in the settings dialog to make sure youre logging to a log file.

**Comment by martin-luy** [comment]
2017-06-21 23:38:10,922 ERROR	rabbitvcs.util.__init__	
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 119, in start
    func.start()
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 44, in start
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 1709, in apply_patch
    self.add_backwards(fullpath)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 1018, in add_backwards
    self.add(head, depth=pysvn.depth.empty)
TypeError: add() got an unexpected keyword argument 'depth'

**Comment by adamplumb** [comment]
Thanks!  That was useful.  I pushed an update to master and would appreciate it if you could test it out for me.

**Comment by martin-luy** [comment]
Hi,
Just tried to use the tarball from master instead of the Ubuntu package: http://wiki.rabbitvcs.org/wiki/install/ubuntu#from-the-tarball
But I don't get the RabbitVCS option with right-click in Nautilus, and also no status symbols in the desktop view. What am I missing?
Here my installation:

martin@martin-Latitude-E6540:~$ sudo apt-get install python-nautilus python-configobj python-gtk2 python-glade2 python-svn python-dbus python-dulwich subversion meld
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
»python-configobj« ist bereits die neuste Version (5.0.6-2).
»python-dbus« ist bereits die neuste Version (1.2.0-3).
»python-glade2« ist bereits die neuste Version (2.24.0-4ubuntu1).
»python-gtk2« ist bereits die neuste Version (2.24.0-4ubuntu1).
»python-svn« ist bereits die neuste Version (1.8.0-1).
»subversion« ist bereits die neuste Version (1.9.3-2ubuntu1).
»meld« ist bereits die neuste Version (3.14.2-1).
»python-dulwich« ist bereits die neuste Version (0.12.0-1build2).
»python-nautilus« ist bereits die neuste Version (1.1-4).
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  ipython python-decorator python-pexpect python-ptyprocess
  python-simplegeneric
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.

martin@martin-Latitude-E6540:~$ cd '/home/martin/Programme/rabbitvcs/rabbitvcs-master' 

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ sudo python setup.py install --install-layout=deb
running install
running build
running build_py
copying rabbitvcs/buildinfo.py -> build/lib.linux-x86_64-2.7/rabbitvcs
running install_lib
copying build/lib.linux-x86_64-2.7/rabbitvcs/buildinfo.py -> /usr/lib/python2.7/dist-packages/rabbitvcs
byte-compiling /usr/lib/python2.7/dist-packages/rabbitvcs/buildinfo.py to buildinfo.pyc
running install_data
running install_egg_info
Removing /usr/lib/python2.7/dist-packages/rabbitvcs-0.16.0.egg-info
Writing /usr/lib/python2.7/dist-packages/rabbitvcs-0.16.0.egg-info
Running gtk-update-icon-cache

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ sudo cp clients/nautilus-3.0/RabbitVCS.py /usr/share/nautilus-python/extensions/.

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ sudo chmod 0777 /usr/share/nautilus-python/extensions/RabbitVCS.py

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ ls -la /usr/share/nautilus-python/extensions
insgesamt 68
drwxr-xr-x 2 root root  4096 Jun 23 07:02 .
drwxr-xr-x 3 root root  4096 Sep 23  2016 ..
-rw-r--r-- 1 root root  2088 Okt 24  2015 clamtk.py
-rw-r--r-- 1 root root  2475 Jun 23 06:35 clamtk.pyc
lrwxrwxrwx 1 root root    42 Mai 23  2013 nautilus-compare.py -> ../../nautilus-compare/nautilus-compare.py
-rw-r--r-- 1 root root  4136 Jun 23 06:35 nautilus-compare.pyc
-rwxrwxrwx 1 root root 24173 Jun 23 07:12 RabbitVCS.py
-rw-r--r-- 1 root root 20030 Jun 23 07:02 RabbitVCS.pyc

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ nautilus -q 
(nautilus:3143): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:3143): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:3143): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(nautilus:3143): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(nautilus:3143): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ pgrep -f service.py | xargs kill

Aufruf:
 kill [Optionen] <pid> […]

Optionen:
 <pid> […]              Signal an alle aufgelisteten <pids> senden
 -<Signal>, -s, --signal <Signal>
                        das zu sendende <Signal> angeben
 -l, --list=[<Signal>]  alle Signalnamen auflisten oder eines
                        in einen Namen konvertieren
 -L, --table            alle Signalnamen in einer Tabelle
                        auflisten

 -h, --help     diese Hilfe anzeigen und beenden
 -V, --version  Versionsinformationen ausgeben und beenden

Für weitere Einzelheiten siehe kill(1).

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ sudo pgrep -f service.py | xargs kill

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ nohup nautilus > /dev/null &
[1] 3162

martin@martin-Latitude-E6540:~/Programme/rabbitvcs/rabbitvcs-master$ nohup: ignoriere Eingabe und leite Standardfehlerausgabe auf Standardausgabe um

**Comment by adamplumb** [comment]
I'm going to have to update the install instructions since they're meant
for nautilus 2.  A couple thoughts:

- Run 'ps aux | grep rabbit' to make sure no rabbitvcs processes are
running.  If they are, kill them
- Run 'ps aux | grep nautilus' to make sure no nautilus processes are
running.  If they are, kil them.
- Just type in 'nautilus' to start nautilus from the command line

2017-06-23 1:30 GMT-04:00 martin-luy <notifications@github.com>:

**Comment by martin-luy** [comment]
Didn't help. There are some warnings when starting Nautilus, but I don't know if they're relevant, and I also don't how to fix them because I'm new to Python. E.g. grepping for "require_version" in the tarball doesn't give any results.

martin@martin-Latitude-E6540:~$ nautilus
Initializing nautilus-dropbox 2.10.0
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 77, in <module>
    from rabbitvcs.util.decorators import timeit, disable
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/decorators.py", line 38, in <module>
    gtk.gdk.threads_init()
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 64, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183

** (nautilus:3064): CRITICAL **: nautilus_menu_provider_get_background_items: assertion 'NAUTILUS_IS_MENU_PROVIDER (provider)' failed

** (nautilus:3064): CRITICAL **: nautilus_menu_provider_get_background_items: assertion 'NAUTILUS_IS_MENU_PROVIDER (provider)' failed
Nautilus-Share-Message: Called "net usershare info" but it failed: Kindprozess »net« konnte nicht ausgeführt werden (Datei oder Verzeichnis nicht gefunden)
