### ISSUE TITLE
Installed on 64-bit Ubuntu 14:04. AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by bassmanitram** [rabbitvcs/rabbitvcs#183]
No menu items. Log contains this:

```
2017-03-10 14:06:06,809 ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 175, in CheckStatus
    invalidate=invalidate)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 49, in check_status
    path_status = self.vcs_client.status(path, summary, invalidate)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 187, in status
    return client.status(path, summarize, invalidate)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/__init__.py", line 200, in status
    all_statuses = self.statuses(path, invalidate=invalidate)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/__init__.py", line 173, in statuses
    gittyup_statuses = self.client.status(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1356, in status
    return self.status_porcelain(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1198, in status_porcelain
    untracked_path = components.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
None
```

**Comment by adamplumb** [comment]
I'm not sure how you're getting this error since there is a check a couple lines above this to prevent this very error.  What version of git are you using?
