### ISSUE TITLE
No Nautilus integration after 0.17 source installation

### ISSUE THREAD

**Issue by kwill** [rabbitvcs/rabbitvcs#215]
I can successfully install and use `rabbitvcs` and `rabbitvcs-nautilus` (v0.16) from distro packages on PureOS (Debian testing / Wayland / GNOME Shell / Nautilus 3.26.0).

But I cannot install 0.17 from source...

**Steps to reproduce:**

* Uninstall distro packages (`rabbitvcs` and `rabbitvcs-nautilus`)
* Install prerequisites

````
sudo apt install \
    python-gtk2 python-configobj python-gobject python-simplejson \
    python-svn subversion python-dulwich git meld \
    python-gtkspellcheck python-tk \
    nautilus python-nautilus python-dbus
````

* Install core from source ([rabbitvcs_installation_record.txt](https://github.com/rabbitvcs/rabbitvcs/files/1406777/rabbitvcs_installation_record.txt))

````
sudo python setup.py install --install-layout=deb
sudo chmod 777 /usr/share/rabbitvcs/configspec.ini
# seems to need this modification
# ran with --record (see attachment)
````

* Copy in Nautilus extension

````
sudo mkdir --parents /usr/share/nautilus-python/extensions
sudo cp ~/Documents/rabbitvcs/clients/nautilus-3.0/RabbitVCS.py /usr/share/nautilus-python/extensions
sudo chmod 777 /usr/share/nautilus-python/extensions/RabbitVCS.py
# otherwise only root can access?
````

* Restart Nautilus

````
nautilus -q
pgrep -f service.py | xargs kill
nohup nautilus >/dev/null 2>&1 &
````

**What should happen?**

When visiting a Git folder in Nautilus, that folder and files within should have emblems.

When right-clicking on a Git folder in Nautilus, RabbitVCS options should be available in the context menu.

**What happens instead?**

No folder decorations. RabbitVCS does not appear in the context menu.

**Notes:**

* See attachment for files created by setup.py
* I can do the following, which implies RabbitVCS core is accessible:

````
$ python2.7
>>> import rabbitvcs
>>> dir(rabbitvcs)
````

* How can I confirm that the Nautilus plugin is launching and/or debug it?

**Comment by adamplumb** [comment]
One thing you can do is check your log file, which is in
~/.config/rabbitvcs.  See if any errors are showing up there.

**Comment by kwill** [comment]
I had some long-standing warnings about Mercurial missing, looks like they were logged by the package installation and (maybe) the source installation. I installed Mercurial, uninstalled RabbitVCS, wiped the logs.

After re-installing from source and visiting Git folder(s), the file `~/.config/rabbitvcs/RabbitVCS.log` is created but empty.

**Comment by kwill** [comment]
I am using Nautilus Compare, so I can confirm that another nautilus-python extension is working as expected.

**Comment by kwill** [comment]
````
~> nautilus -q
~> nautilus --no-desktop
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 70, in <module>
    from rabbitvcs.vcs import VCS
ImportError: No module named rabbitvcs.vcs
````

**Comment by kwill** [comment]
And another attempt...

````
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 189, in __init__
    pixbuf = GdkPixbuf.Pixbuf.new_from_file(icon_path)
GLib.Error: g-file-error-quark: Failed to open file '/usr/share/icons/hicolor/scalable/actions/rabbitvcs-settings.svg': Permission denied (2)
````

**Comment by kwill** [comment]
Added

````
sudo chmod ugo+r /usr/share/rabbitvcs/*
sudo chmod ugo+r /usr/share/icons/hicolor/scalable/actions/rabbitvcs*
sudo chmod ugo+r /usr/share/icons/hicolor/scalable/apps/rabbitvcs*
sudo chmod ugo+r /usr/share/icons/hicolor/16x16/actions/rabbitvcs*
sudo chmod ugo+r /usr/share/icons/hicolor/16x16/apps/rabbitvcs*
````

RabbitVCS context menu is now appearing.

**Comment by kwill** [comment]
`~/.config/rabbitvcs/RabbitVCS.log` now contains

````
2017-10-24 18:13:08,081 ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Error.ServiceUnknown: The name :1.583 was not provided by any .service files
None
````

**Comment by adamplumb** [comment]
You might need to restart the checkerservice.  Open up rabbitvcs settings and there should be a tab that will allow you to kill it.

**Comment by kwill** [comment]
Thanks! Logs generated after restarting the service and restarting Nautilus:

````
2017-10-24 19:18:08,458 DEBUG	rabbitvcs.services.service	Started process: 15997
2017-10-24 19:18:08,602 WARNING	rabbitvcs.util.locale	Could not set default locale (LANG: en_ZA.UTF-8)
2017-10-24 19:18:08,602 WARNING	rabbitvcs.util.locale	Manually set encoding to UTF-8
2017-10-24 19:18:08,602 DEBUG	rabbitvcs.services.checkerservice:main	Checker: starting service: /org/google/code/rabbitvcs/StatusChecker (15997)
2017-10-24 19:18:12,458 DEBUG	rabbitvcs.services.checkerservice:main	Quitting main loop...
2017-10-24 19:18:12,460 DEBUG	rabbitvcs.services.checkerservice:main	Checker: ended service: /org/google/code/rabbitvcs/StatusChecker (15997)
2017-10-24 19:18:12,503 DEBUG	rabbitvcs.services.service	Started process: 16007
2017-10-24 19:18:12,627 WARNING	rabbitvcs.util.locale	Could not set default locale (LANG: en_ZA.UTF-8)
2017-10-24 19:18:12,627 WARNING	rabbitvcs.util.locale	Manually set encoding to UTF-8
2017-10-24 19:18:12,627 DEBUG	rabbitvcs.services.checkerservice:main	Checker: starting service: /org/google/code/rabbitvcs/StatusChecker (16007)
2017-10-24 19:19:25,621 DEBUG	rabbitvcs.util.extensions.nautilus	Re-scanning settings
````

Potentially relevant bits from `nautilus --no-desktop` output (or could be unrelated):

````
** (nautilus:16383): CRITICAL **: nautilus_menu_provider_get_background_items: assertion 'NAUTILUS_IS_MENU_PROVIDER (provider)' failed
Nautilus-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.
````

(guessing that is totally unrelated)

````
(nautilus:16383): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
````

````
DEBUG	rabbitvcs.ui.contextmenuitems	is_process_still_alive() for pid: 16636
DEBUG	rabbitvcs.ui.contextmenuitems	None
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/widget.py:136: GtkWarning: IA__gtk_tree_model_filter_convert_iter_to_child_iter: assertion 'filter_iter->stamp == filter->priv->stamp' failed
  real_iter = model.convert_iter_to_child_iter(iter)
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/widget.py:138: GtkWarning: gtk_list_store_get_path: assertion 'iter->stamp == GTK_LIST_STORE (tree_model)->stamp' failed
  row = real_model[real_model.get_path(real_iter)]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/widget.py", line 138, in filter_router
    row = real_model[real_model.get_path(real_iter)]
TypeError: could not parse subscript as a tree path
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py:1679: GtkWarning: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
  gtk.main()
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py:1679: Warning: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed
  gtk.main()
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py:1679: Warning: unable to set property 'text' of type 'gchararray' from value of type '(null)'
  gtk.main()
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py:1679: Warning: unable to set property 'markup' of type 'gchararray' from value of type '(null)'
  gtk.main()
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py:1679: GtkWarning: gtk_tree_model_filter_iter_next: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
  gtk.main()
/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py:1679: GtkWarning: /build/gtk+2.0-1aCJs4/gtk+2.0-2.24.31/gtk/gtktreeview.c:6293 (do_validate_rows): assertion `gtk_tree_model_iter_next (tree_view->priv->model, &iter)' failed.
There is a disparity between the internal view of the GtkTreeView,
and the GtkTreeModel.  This generally means that the model has changed
without letting the view know.  Any display from now on is likely to
be incorrect.

  gtk.main()
DEBUG	rabbitvcs.ui.contextmenuitems	is_process_still_alive() for pid: 16636
DEBUG	rabbitvcs.ui.contextmenuitems	None
DEBUG	rabbitvcs.ui.contextmenuitems	is_process_still_alive() for pid: 16636
DEBUG	rabbitvcs.ui.contextmenuitems	None
````

**Comment by kwill** [comment]
I got an update to my desktop icon package, and emblems then appeared. I'm not sure how to make sure this happens on a fresh installation, but the issue has resolved itself.

**Comment by jflambert** [comment]
I followed the installation procedure on Ubuntu 18.04 and got the same error message you got:

sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.

**Comment by adamplumb** [comment]
This is probably a separate issue but it is a pretty easy fix.  You'll need to find your extension file (usually in /usr/share/nautilus-python or ~/.local/share/nautilus-python) and add:
```
import gi
gi.require_version('Nautilus', '3.0')
```
