### ISSUE TITLE
RabbitVCS does not handle non-UTF8 filenames where 8th bit is set

### ISSUE THREAD

**Issue by AndersBlomdell** [rabbitvcs/rabbitvcs#231]
On Fedora-28 (rabbitvcs-0.17.1), non UTF8 filenames (latin1, latin15, etc) in filenames results in this 
in the logfiles:

```
2018-05-23 13:15:41,259 ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Python.UnicodeDecodeError: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/services/checkerservice.py", line 184, in GenerateMenuConditions
    path_dict = self.status_checker.generate_menu_conditions(upaths)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/services/statuschecker.py", line 56, in generate_menu_conditions
    conditions = MainContextMenuConditions(self.vcs_client, paths)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/util/contextmenu.py", line 1210, in __init__
    self.generate_statuses(paths)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/util/contextmenu.py", line 1220, in generate_statuses
    statuses_tmp = self.vcs_client.statuses(path)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/vcs/__init__.py", line 234, in statuses
    return client.statuses(path, recurse=recurse, invalidate=invalidate)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/vcs/git/__init__.py", line 175, in statuses
    gittyup_statuses = self.client.status(path)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1598, in status
    return self.status_porcelain(path)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1370, in status_porcelain
    (files, directories) = self._read_directory_tree(path)
  File "/usr/lib/python2.7/site-packages/rabbitvcs/vcs/git/gittyup/client.py", line 288, in _read_directory_tree
    for root, dirs, filenames in os.walk(path, topdown=True):
  File "/usr/lib64/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
None
```

**Comment by monnerat** [comment]
There is currently an experimental branch named `encoding` in the github repo. It is supposed fixing most encoding-related problems (though filenames with invalid characters in subversion repos are not yet handled). Can you check it out and reinstall everything from there to see if your problems disappear?
Once you'll have installed this version, you must restart the service checker (menu --> RabbitVCS Git --> Settings --> Status Checker --> Restart Checker).

Thanks in advance for feedback.

**Comment by monnerat** [comment]
It should be fixed now in the master branch. If the problem persists, please reopen this issue. Thanks.

**Comment by AlexNk** [comment]
Reproduces with v, 0.18 - the logs contain some messages in Ukrainian:

```
2023-06-12 17:47:48,631 ERROR	rabbitvcs.util.__init__	
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/util/__init__.py", line 123, in start
    func.start()
  File "/usr/lib/python3/dist-packages/rabbitvcs/util/__init__.py", line 47, in start
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/rabbitvcs/vcs/git/__init__.py", line 788, in log
    items = self.client.log(path, skip, limit, revision.primitive(), showtype)
  File "/usr/lib/python3/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1890, in log
    "path": self.string_unescape(file_line[2]),
  File "/usr/lib/python3/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 357, in string_unescape
    s = s.encode(IDENTITY_ENCODING)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 25-31: ordinal not in range(256)
2023-06-12 17:47:48,632 ERROR	rabbitvcs.ui.action	'latin-1' codec can't encode characters in position 25-31: ordinal not in range(256)
NoneType: None
```
