### ISSUE TITLE
Selecting Items in list when I want to commit (gtk3 branch)

### ISSUE THREAD

**Issue by jaheme127** [rabbitvcs/rabbitvcs#259]
Hey,

I got the following error messages when I try to commit something with git in Nemo file manager 4.0 - It does not happen always. It happen when I try to select an Item in the list

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 470, in toggled_cb
    realpath = self._realpath(path)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 463, in _realpath
    path = self.sorted.convert_path_to_child_path(visible_path)
TypeError: argument sorted_path: Expected Gtk.TreePath, but got str
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 470, in toggled_cb
    realpath = self._realpath(path)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 463, in _realpath
    path = self.sorted.convert_path_to_child_path(visible_path)
TypeError: argument sorted_path: Expected Gtk.TreePath, but got str
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 470, in toggled_cb
    realpath = self._realpath(path)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 463, in _realpath
    path = self.sorted.convert_path_to_child_path(visible_path)
TypeError: argument sorted_path: Expected Gtk.TreePath, but got str
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 470, in toggled_cb
    realpath = self._realpath(path)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 463, in _realpath
    path = self.sorted.convert_path_to_child_path(visible_path)
TypeError: argument sorted_path: Expected Gtk.TreePath, but got str
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 470, in toggled_cb
    realpath = self._realpath(path)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 463, in _realpath
    path = self.sorted.convert_path_to_child_path(visible_path)
TypeError: argument sorted_path: Expected Gtk.TreePath, but got str
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 470, in toggled_cb
    realpath = self._realpath(path)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/widget.py", line 463, in _realpath
    path = self.sorted.convert_path_to_child_path(visible_path)
TypeError: argument sorted_path: Expected Gtk.TreePath, but got str

**Comment by monnerat** [comment]
There has been a lot of changes since then in RabbitVCS: can you try with the latest master and report here? Thanks.

**Comment by jaheme127** [comment]
Thank you the issue is resolved!

**Comment by monnerat** [comment]
@jaheme127 : Thanks for feedback !
