### ISSUE TITLE
No Commit Possible when running rabbitvcs with old dulwich version.

### ISSUE THREAD

**Issue by jaheme127** [rabbitvcs/rabbitvcs#260]
When I try to commit something I got the following issue with dulwich 0.18.5 --- this issue does not happen with dulwich 0.19.11:

('GOT REPO PATH', '/home/jan/Daten/Repo/Meine/egswebsite3/master')
ERROR	rabbitvcs.util.__init__	
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 120, in start
    func.start()
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 45, in start
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/__init__.py", line 544, in commit
    commit_all)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 834, in commit
    merge_heads=parents)
  File "/usr/lib/python2.7/dist-packages/dulwich/repo.py", line 590, in do_commit
    committer = self._get_user_identity()
  File "/usr/lib/python2.7/dist-packages/dulwich/repo.py", line 521, in _get_user_identity
    config.get((b"user", ), b"email") + b">")
  File "/usr/lib/python2.7/dist-packages/dulwich/config.py", line 429, in get
    raise KeyError(name)
KeyError: 'name'

The error can happen in the gtk3 as in the master branch and happens in python2 and python3 environment. 

Maybe updating the requirements? Or a workaround? Other suggestions?

**Comment by monnerat** [comment]
Dulwich has considerably changed between 0.18.5 and 0.19.0, in particular the _get_user_identity() method has been almost completely rewritten. Thus I presume this was a Dulwich bug.
I successfully tested RabbitVCS with Dulwich 0.19.2. RabbitVCS requirements should be changed to a minimum of (probably) 0.19.0.
