### ISSUE TITLE
Can't log into SVN with RabbitVCS

### ISSUE THREAD

**Issue by jf352** [rabbitvcs/rabbitvcs#264]
Specific exception that occurs when trying to access an SVN repository (this is after checkout/install) is:

"unhandled exception in callback_get_login"

With no further details on the GUI, but when I run nautilus from a terminal with NAUTILUS_DEBUG="All", we see:

`Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
TypeError: PyCXX: Error creating object of type N2Py5TupleE from <bound method Authentication.run of <rabbitvcs.ui.dialog.Authentication instance at 0x7fba6c024248>>
ERROR	rabbitvcs.util.__init__	
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 120, in start
    func.start()
  File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 45, in start
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 1675, in list
    recurse=recurse)
ClientError: unhandled exception in callback_get_login
ERROR	rabbitvcs.ui.action	unhandled exception in callback_get_login`

**Comment by jf352** [comment]
Apparently this is because RabbitVCS only supports plaintext authentication rather than storing in gpg, keyring etc. Is this a feature likely to be added?
