### ISSUE TITLE
Svn log: 'utf8' codec can't decode byte error

### ISSUE THREAD

**Issue by fabiodeuzebio** [rabbitvcs/rabbitvcs#271]
While viewing the Svn log, I got the following error
![image](https://user-images.githubusercontent.com/5614991/60437566-0712cf00-9be5-11e9-8916-1d9c6b88cde5.png)

Here is the contents of the log file
`2019-07-01 09:43:02,432 ERROR	rabbitvcs.util.__init__	
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 120, in start
    func.start()
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 45, in start
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py", line 478, in refresh
    msg = helper.format_long_text(item.message, cols = 80, line1only = True)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/helper.py", line 193, in format_long_text
    text = text.strip().replace(u"\n", LINE_BREAK_CHAR)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
2019-07-01 09:43:02,433 ERROR	rabbitvcs.ui.action	'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
None`

**Comment by pinguingman** [comment]
Have similar issue:
![image](https://user-images.githubusercontent.com/31766174/60651905-d97d8e00-9e4f-11e9-96ab-aa0d2088a893.png)

**Comment by gabrielfin** [comment]
I'm having the same issue. Don't know what's causing it but here's a quick and dirty hack:

In `/usr/lib/python2.7/dist-packages/rabbitvcs/util/helper.py` line 193 add:
```py
text = text.decode('utf-8')
```
right before
```py
text = text.strip().replace(u"\n", LINE_BREAK_CHAR)
```

**Comment by monnerat** [comment]
There is currently an experimental branch named `encoding` in the github repo. It is supposed fixing most encoding-related problems (though filenames with invalid characters in subversion repos are not yet handled). Can you check it out and reinstall everything from there to see if your problems disappear?
Once you'll have installed this version, you must restart the service checker (menu --> RabbitVCS Git --> Settings --> Status Checker --> Restart Checker).

Thanks in advance for feedback.

**Comment by fabiodeuzebio** [comment]
I reinstalled everything from there as suggested but the problem still occurs.

`2019-08-14 07:57:37,636 ERROR	rabbitvcs.util.__init__	
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 120, in start
    func.start()
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/__init__.py", line 45, in start
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/log.py", line 482, in refresh
    msg = helper.format_long_text(item.message, cols = 80, line1only = True)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/helper.py", line 181, in format_long_text
    text = text.strip().replace(u"\n", LINE_BREAK_CHAR)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
2019-08-14 07:57:37,636 ERROR	rabbitvcs.ui.action	'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
None`

**Comment by monnerat** [comment]
Many thanks for the feedback.
I just pushed commit e0abbbc to the `encoding` branch: this should resolve your issue.

**Comment by fabiodeuzebio** [comment]
With this setting now it worked, Thanks !!

**Comment by monnerat** [comment]
Many thanks for reporting. This will land in master branch in a few days or weeks, when I'll have some more feedbacks on it from other issues.
Thanks again.

**Comment by monnerat** [comment]
It should be fixed now in the master branch. If the problem persists, please reopen this issue. Thanks.
