### ISSUE TITLE
Error on startup (checkerservice)

### ISSUE THREAD

**Issue by jaheme127** [rabbitvcs/rabbitvcs#274]
I got the following error messages on startup. Maybe someone can remove them? RabbitVCS continues to work perfectly.

ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method' % method_name)
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetLocale is not a valid method
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 267, in _connect_to_checker
    self.status_checker.SetLocale(*locale.getlocale(locale.LC_MESSAGES))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method' % method_name)
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetLocale is not a valid method

ERROR:rabbitvcs.services.checkerservice:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method' % method_name)
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetLocale is not a valid method
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 267, in _connect_to_checker
    self.status_checker.SetLocale(*locale.getlocale(locale.LC_MESSAGES))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method' % method_name)
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetLocale is not a valid method

**Comment by monnerat** [comment]
This is a rather new RabbitVCS DBus method and, as it appears you just updated RabbitVCS, the old status checker is still running.
This problem will probably be cleared by:
`
Menu --> RabbitVCS Git --> Settings --> Status Checker --> Restart Checker`

or by rebooting your computer !

**Comment by jaheme127** [comment]
Thank you, the error does not appear anymore.
