### ISSUE TITLE
undefined global 'urllib' in helper.py

### ISSUE THREAD

**Issue by GrantEdwards** [rabbitvcs/rabbitvcs#283]
In 0.17 browser, clicking update for a subversion https: url throws an exception:
~~~
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/rabbitvcs/ui/browser.py", line 170, in on_refresh_clicked
    self.load()
  File "/usr/lib64/python2.7/site-packages/rabbitvcs/ui/browser.py", line 141, in load
    rabbitvcs.util.helper.quote_url(self.url), 
  File "/usr/lib64/python2.7/site-packages/rabbitvcs/util/helper.py", line 827, in quote_url
    path_quoted = urllib.quote(path)
NameError: global name 'urllib' is not defined
~~~

Adding `import urllib` at the top of helper.py seems to fix it.

**Comment by monnerat** [comment]
Release 0.17.1 already fixed it. However I would recommend to use a master branch snapshot that fixes a LOT of bugs, uses gtk3 and introduces Python 3 compatibility.
If the version you use comes from a distribution package, please report to the packager (using your distro's bug reporting tool) and ask for a more recent version.
Thanks for reporting.
