### ISSUE TITLE
Ubuntu 20.04 Python 3.8 urllib unquote error

### ISSUE THREAD

**Issue by ugurbor** [rabbitvcs/rabbitvcs#292]
I have installed it manually (as I did on 19.10 before). Fixed it by removing helper.unquote_url from switch.py line 63.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/switch.py", line 108, in <module>
    window = switch_factory(args[0], revision=options.revision)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/switch.py", line 98, in switch_factory
    return classes_map[guess["vcs"]](path, revision)
  File "/usr/lib/python3/dist-packages/rabbitvcs/ui/switch.py", line 63, in __init__
    self.repositories.set_child_text(helper.unquote_url(self.svn.get_repo_url(self.path)))
  File "/usr/lib/python3/dist-packages/rabbitvcs/util/helper.py", line 958, in unquote_url
    path_unquoted = unquote(path)
  File "/usr/lib/python3/dist-packages/rabbitvcs/util/helper.py", line 916, in _unquote
    return six.moves.urllib.parse.unquote(text,
  File "/usr/lib/python3.8/urllib/parse.py", line 634, in unquote
    if '%' not in string:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by monnerat** [comment]
Thanks for your bug report. A fix has been committed in c7207ad
