### ISSUE TITLE
Thunar Install Not Working

### ISSUE THREAD

**Issue by metal450** [rabbitvcs/rabbitvcs#297]
I've got about 4 hours into trying to get this running on Thunar, so far unfortunately with no success.  The install process detailed in the instructions most certainly doesn't work.  I'm running Kubuntu 20.04.

First, install Thunar:

     sudo apt install thunar

And a couple of the rabbitvcs dependencies that are actually available in the repo:

     python-gobject python-dbus

Next, I need to install thunarx-python.  It's missing in the repo, so I install thunarx-python_0.5.1-2_amd64.deb, download directly from https://ubuntu.pkgs.org/19.10/ubuntu-universe-amd64/thunarx-python_0.5.1-2_amd64.deb.html

Likewise, python-configobj is missing in the repo, so I install the deb from https://ubuntu.pkgs.org/19.10/ubuntu-universe-amd64/python-configobj_5.0.6-3_all.deb.html

Now the basic Rabbit install:

     git clone https://github.com/rabbitvcs/rabbitvcs
     cd rabbitvcs
     sudo python setup.py install --install-layout=deb
     sudo mkdir -p /usr/share/thunarx-python/extensions
     sudo cp clients/thunar/RabbitVCS.py /usr/share/thunarx-python/extensions

To see what's going on, I'll run Thunar with thunarx-python debugging enabled:

     THUNARX_PYTHON_DEBUG=all /usr/bin/thunar

The result:

    thunar_extension_initialize: entered
    thunarx_python_load_dir: entered dirname=/home/metal450/.local/share/thunarx-python/extensions
    thunarx_python_load_dir: entered dirname=/usr/share/thunarx-python/extensions
    thunarx_python_init_python: entered
    thunarx-python: Setting GI_TYPELIB_PATH to /usr/lib/x86_64-linux-gnu/girepository-1.0
    thunarx-python: g_module_open /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
    thunarx-python: Py_Initialize
    thunarx-python: PySys_SetArgv
    thunarx-python: Sanitize the python search path
    thunarx-python: init_pygobject
    thunarx-python: import Thunarx
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 129, in require_version
        raise ValueError('Namespace %s not available' % namespace)
    ValueError: Namespace Thunarx not available
    Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 133, in load_module
        'introspection typelib not found' % namespace)
    ImportError: cannot import name Thunarx, introspection typelib not found

    (thunar:14773): thunarx-python-WARNING **: 11:50:40.747: thunarx_python_init_python failed
    Traceback (most recent call last):
    File "/usr/share/thunarx-python/extensions/RabbitVCS.py", line 41, in <module>
        from gi.repository import GObject, Gtk, Thunarx
    File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 133, in load_module
        'introspection typelib not found' % namespace)
    ImportError: cannot import name Thunarx, introspection typelib not found
    thunarx_python_load_dir: entered dirname=/usr/share/plasma/thunarx-python/extensions
    thunarx_python_load_dir: entered dirname=/usr/local/share/thunarx-python/extensions
    thunarx_python_load_dir: entered dirname=/usr/share/thunarx-python/extensions
    thunarx_python_init_python: entered
    Traceback (most recent call last):
    File "/usr/share/thunarx-python/extensions/RabbitVCS.py", line 41, in <module>
        from gi.repository import GObject, Gtk, Thunarx
    File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 133, in load_module
        'introspection typelib not found' % namespace)
    ImportError: cannot import name Thunarx, introspection typelib not found
    thunarx_python_load_dir: entered dirname=/var/lib/snapd/desktop/thunarx-python/extensions
    thunarx_python_load_dir: entered dirname=/usr/lib/x86_64-linux-gnu/thunarx-3/python
    thunar_extension_list_types: entered

That's as far as I'm able to get.  It looks like it wants the Thunarx typelib in GI_TYPELIB_PATH, which is /usr/lib/x86_64-linux-gnu/girepository-1.0.  Some googling makes it seem like this should be Thunarx-3.0.typelib, where that file is included with thunar itself (i.e. see https://www.archlinux.org/packages/extra/x86_64/thunar/files/).  But it isn't, and there's no such file anywhere on my system, and search as I might I cannot figure out where it's supposed to come from.  So 4 hours later, I'm still stumped & unable to get Rabbit working :/

**Comment by adamplumb** [comment]
You're right that you need that typelib file.  Without it you won't be able
to import the ThunarX gobject introspection bindings from thunar.    I'm
not sure what happened but it could be an issue with the thunarx-python
package you downloaded.  I would uninstall that and install thunarx-python
from source and see what happens.  That should generate and install the
typelib file for you.

**Comment by metal450** [comment]
That seems to get me to the same issue, just from another angle: it's looking for this mystery "thunarx-3" library that doesn't seem to exist anywhere.

    sudo apt install xfce4-dev-tools gtk-doc-tools python-dev
    git clone https://github.com/xfce-mirror/thunarx-python
    cd thunarx-python
    ./autogen.sh

The output ends with:

    checking for python version... 2.7
    checking for python platform... linux2
    checking for python script directory... ${prefix}/lib/python2.7/dist-packages
    checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
    checking for headers required to compile python extensions... found
    checking for libraries required to embed python... yes
    Package thunarx-3 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `thunarx-3.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'thunarx-3' found
    thunarx-3 is required

Here's another plugin that refers to this mysterious "thunarx-3" package that doesn't seem to be available anywhere: https://github.com/xfce-mirror/thunar-shares-plugin/blob/master/README

More googling made me think it might be libthunarx-3-0, but that was already installed.  So building from source doesn't seem possible either...

**Comment by metal450** [comment]
Related, should this really still be using python 2.7 instead of python3?

**Comment by metal450** [comment]
Spent another hour trying to see if I could get thunarx-python-0.3 (instead of 0.5, in case it's a python2 vs python3 issue). But that ended up in a mess of unsatisfiable dependencies that I was trying to install one at a time, before it became too unmanageable to continue.

**Comment by metal450** [comment]
More progress: if I download the rpm from https://download-ib01.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/t/Thunar-1.8.11-1.el8.x86_64.rpm, manually extract the missing typelib, and manually move it to /usr/lib/x86_64-linux-gnu/girepository-1.0, it gets farther.

Now I can see the menus.  But overlay icons don't work, and about half of the menu entries display question marks instead of real strings.

This is absolutely nothing like the published install instructions.  I'm in disbelief at how difficult this is. I've never spent so many hours trying to install one piece of software.

**Comment by adamplumb** [comment]
You'll need a version of thunar that generates thunarx 3. I think that
happened around 1.7 or 1.8.  Before that you'll need to use an older
version of thunarx python and rabbitvcs for thunarx 2

**Comment by adamplumb** [comment]
FYI overlay emblems don't work in thunar. It isnt a supported feature.

**Comment by metal450** [comment]
>>>overlay emblems don't work in thunar. It isnt a supported feature.

....Crap.  I *really* wish I'd noticed that in the readme, as that was pretty much the primary reason I was even working on this :'(

Does that leave Nautilus as the most lightweight file manager that supports this?  I'm running KDE & trying to avoid excess bloat as much as possible - my understanding is that Nemo is pretty beefy in terms of needing all the Cinnamon common code to be able to run. I picked Thunar just because it seemed to be the lightest weight option.

>>You'll need a version of thunar that generates thunarx 3. I think that happened around 1.7 or 1.8.

Was running 1.8.14.

**Comment by adamplumb** [comment]
Nautilus is our primary client and the only one that supports overlay
emblems. Dolphin might support emblems but I'm not sure.

**Comment by metal450** [comment]
>>Dolphin might support emblems but I'm not sure.

If Dolphin were supported, that would be awesome - it would supersede this whole need for a 2nd file manager, but there didn't seem to even be git menu support for Dolphin, let alone icon overlays.  (Dolphin itself actually supports git icon overlays, so in that case, I'd only need the menus - however, https://github.com/rabbitvcs/rabbitvcs/tree/master/clients/dolphin only contained a menu for SVN.  Did I by chance miss something elsewhere?)

>>Nautilus is our primary client and the only one that supports overlay
emblems

Alright, nautilus it is then.  Following the install instructions again, this time using the PPA and package rabbitvcs-nautilus (note: the instructions say rabbitvcs-nautilus3, but that package doesn't exist), Nautilus now gives the error:

    ERROR:dbus.connection:Unable to set arguments (None, None) according to signature None: <class 'TypeError'>: Don't know which D-Bus type to use to encode type "NoneType"
    Traceback (most recent call last):
    File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 208, in __init__
        self.status_checker = StatusChecker()
    File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 258, in __init__
        self._connect_to_checker()
    File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 270, in _connect_to_checker
        self.status_checker.SetLocale(*locale.getlocale(locale.LC_MESSAGES))
    File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
        return self._proxy_method(*args, **keywords)
    File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
        return self._connection.call_blocking(self._named_service,
    File "/usr/lib/python3/dist-packages/dbus/connection.py", line 643, in call_blocking
        message.append(signature=signature, *args)
    TypeError: Don't know which D-Bus type to use to encode type "NoneType"

**Comment by adamplumb** [comment]
I'm not sure what's in that package so what I would do instead is install
the Nautilus client directly from our codebase. There are install
instructions in the client/Nautilus folder.

**Comment by metal450** [comment]
If that package isn't a good way to install, maybe best not to have it listed as the install instructions? http://wiki.rabbitvcs.org/wiki/install/ubuntu

Reinstalled with:

    sudo apt install nautilus python-dbus python3-nautilus python3-configobj python3-svn
    git clone https://github.com/rabbitvcs/rabbitvcs
    cd rabbitvcs
    sudo python3 setup.py install --install-layout=deb
    sudo cp clients/nautilus/RabbitVCS.py /usr/share/nautilus-python/extensions
    nautilus -q

Note: the instructions listed nautilus-python, which didn't exist; I had to change to python3-nautilus.  Similarly with python-configobj -> python3-configobj, python-svn -> python3-svn, dulwich -> python3-dulwich.

Still, the behavior is similar:

    ERROR   rabbitvcs.services.checkerservice       org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/dbus/service.py", line 256, in _method_reply_return
        reply.append(signature=signature, *retval)
    TypeError: Don't know which D-Bus type to use to encode type "NoneType"

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/dbus/service.py", line 755, in _message_cb
        _method_reply_return(connection, message, method_name, signature, *retval)
    File "/usr/lib/python3/dist-packages/dbus/service.py", line 261, in _method_reply_return
        signature = reply.guess_signature(retval) + ' (guessed)'
    TypeError: Don't know which D-Bus type to use to encode type "NoneType"
    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 270, in _connect_to_checker
        self.status_checker.SetLocale(*locale.getlocale(locale.LC_MESSAGES))
    File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
        return self._proxy_method(*args, **keywords)
    File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
        return self._connection.call_blocking(self._named_service,
    File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
        reply_message = self.send_message_with_reply_and_block(
    dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/dbus/service.py", line 256, in _method_reply_return
        reply.append(signature=signature, *retval)
    TypeError: Don't know which D-Bus type to use to encode type "NoneType"

**Comment by metal450** [comment]
Commenting out /usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py line 270 fixes the exception, & makes the overlay icons work. Using the menus still yields an exception (locale.Error: unsupported locale setting) - which isn't surprising - but clearly the bug is on that line.

**Comment by metal450** [comment]
Here's the issue:

locale.getlocale(locale.LC_MESSAGES) -> returns (None, None)

In KDE, LC_Messages is set to LC_MESSAGES="C.UTF-8".  I guess "C" means "Default."  In any case, what that line needs is a fallback to something like locale.getlocale(0) if the LC_MESSAGES locale yields an unworking (None, None).

After fixing that line, the same bug is present in other places too.  For example, /usr/lib/python3/dist-packages/rabbitvcs/vcs/git/.__init__.py line 824. It looks like none of the setlocale() calls check for success (i.e. errors are ignored), which is what's breaking it on KDE.  Note: this is a default KDE install, I haven't messed with my locale.

**Comment by jesus2099** [comment]
I read here that emblems are not supported by Thunar and indeed the Thunar screenshot on rabbitvcs.org doesn't show green check mark icon overlays on files.

But reading the Xfce forum, it seems that [emblems are hopefully supported](https://forum.xfce.org/search.php?action=search&keywords=thunar+emblem&author=&forums=&search_in=0&sort_by=0&sort_dir=DESC&show_as=topics) now..

I'm relieved but I can still not install on my Debian Xfce as I do see **rabbitvcs-core** and **rabbitvcs-cli** packages but not **rabbitvcs-thunar** available in the Synaptic package manager.

Reading other tickets, it seems that it may be because current Thunar is not yet supported?
It's not really clear though, https://github.com/rabbitvcs/rabbitvcs/issues/239#issuecomment-513457610 says OK then later https://github.com/rabbitvcs/rabbitvcs/issues/145#issuecomment-520328633 reports KO.

---

I hope I am not too off-topic.
I hesitated before adding a comment here as a forum post would have been more appropriate (but all there is apparently is IRC channel, empty when I joined, and a Google group, I created a Google account but it says it doesn't exist or is not public, and mailing list is not convenient for community discussions, newbie stuff and searchable community found solutions). A forum would be great (even if using an existing forum).

**Comment by adamplumb** [comment]
Emblems are supported in thunar but not available for extensions to set
them unfortunately. It's something I attempted some years ago but in the
end the thunar team decided they didn't think it was the right way to go.

I would advise installing manually from GitHub as I'm not sure what the
state of the packages in Ubuntu is.

**Comment by jesus2099** [comment]
I am new to Linux so I don't know much things. I'm absolute beginner, so pardon me if I say nonsense.

It seems that years ago Thunar was not using the same emblem code.

They now use GVFS and here would be a way to [set emblems with GVFS](https://stackoverflow.com/questions/2180432/how-to-change-icon-emblem-of-a-directory-from-bash).

The G in GVFS stands for Gnome, so maybe it's now same as Nautilus?

**Comment by monnerat** [comment]
> They now use GVFS and here would be a way to set emblems with GVFS.

These are GVFS persistent emblems that thunar allows to set via the properties contextual menu, while RabbitVCS needs setting volatile emblems dynamically: this last feature is not supported by thunar. Quoting Adam's reply:

> Emblems are supported in thunar but not available for extensions to set
> them unfortunately.

**Comment by jesus2099** [comment]
I think we should create a Thunar ticket for this, as it would be useful for any VCS integration.
Is there already such a ticket?

**Comment by monnerat** [comment]
I don't think it will have any effect: Citing Adam again:

> It's something I attempted some years ago but in the end the thunar team decided they didn't think it was the right way to go.

Thus you'll have to live with it :-(

**Comment by jesus2099** [comment]
I got a rather positive comment at https://gitlab.xfce.org/thunar-plugins/thunar-vcs-plugin/-/issues/11#note_10539 saying _thunarx API for emblems is already on the roadmap_. So it's at least a wish now.

**Comment by monnerat** [comment]
> thunarx API for emblems is already on the roadmap.

Good! Let's see how it progresses: this does not seem to be at a high priority and the wagon cannot go faster that the locomotive!

Please note that Nemo and Caja clients already support emblems as Nautilus client does.

**Comment by adamplumb** [comment]
The main issue around setting emblems in thunar now is that the thunar
extension framework doesn't have a way to tell RabbitVCS which files it is
looking at.  The Nautilus extension framework says "the user is looking at
these files/folders, do you want to put an emblem on them?", which is
really convenient.  The Thunar extension framework doesn't do that, so the
only way to set an emblem is to set the emblem metadata from a separate
process, and hopefully Thunar will see it and display it (theoretically
this should work).  The issue is you need that separate process to know
what are your version controlled folders, watch that folder constantly
(through inotify), walk the entire folder recursively, and apply emblems as
needed.  The user would probably need to register which folders they want
watched, which is something Nautilus RabbitVCS doesn't require.

**Comment by adamplumb** [comment]
I think the main remaining issue is that once a status changes on a file or
folder, I don't know if there is a way to indicate to thunar that it should
render the new emblem.  Right now it seems you would need to manually
reload the folder (ctrl+r) which kind of makes this less attractive.

**Comment by monnerat** [comment]
> The main issue around setting emblems in thunar now is that the thunar extension framework doesn't have a way to tell RabbitVCS which files it is looking at.

Sure, this is a problem. I would expect that this notification interface will be part of the planned feature. Since there is nothing in tunarx right now, we can only wait... and hopefully see.
