### ISSUE TITLE
configspec.ini not found after python3 setup.py install --user   

### ISSUE THREAD

**Issue by GrantEdwards** [rabbitvcs/rabbitvcs#298]
I have the cli client in a directory on my PATH (`~/bin`).

After doing a user install with
    `$ python3 setup.py install --user`

The module is in
    `~/.local/lib/python3.7/site-packages/rabbitvcs`

The setupconfig.ini file is in
    `~/.local/share/rabbitvcs/configspec.ini`

However, that's not one of the paths searched for configspec.ini, so you get this:
~~~
$ rabbitvcs
Traceback (most recent call last):
  File "/home/grante/bin/rabbitvcs", line 27, in <module>
    from rabbitvcs.util.helper import launch_ui_window
  File "/home/grante/.local/lib/python3.7/site-packages/rabbitvcs/util/__init__.py", line 24, in <module>
    from rabbitvcs.util.log import Log
  File "/home/grante/.local/lib/python3.7/site-packages/rabbitvcs/util/log.py", line 49, in <module>
    from rabbitvcs.util.settings import SettingsManager, get_home_folder
  File "/home/grante/.local/lib/python3.7/site-packages/rabbitvcs/util/settings.py", line 90, in <module>
    SETTINGS_SPEC = find_configspec()
  File "/home/grante/.local/lib/python3.7/site-packages/rabbitvcs/util/settings.py", line 88, in find_configspec
    raise IOError("Cannot find a configspec.ini file")
OSError: Cannot find a configspec.ini file
~~~

A symlink fixes this:

~~~
$ ls -l /usr/local/share/rabbitvcs/
total 0
lrwxrwxrwx 1 root root 50 May 28 14:31 configspec.ini -> /home/grante/.local/share/rabbitvcs/configspec.ini
~~~

But, it would be nice if the place where the configspec.ini file is installed by setup.py was on the list of locations where the code looks for configspec.ini.

**Comment by monnerat** [comment]
Thanks for the problem report.
The --user option was not properly handled in setup.py. Commit f319c2f fixes it. Please reinstall from master and report here. Thanks.

**Comment by GrantEdwards** [comment]
Yes thanks, that fixes it.

**Comment by monnerat** [comment]
Thanks for feedback. Closing.
