### ISSUE TITLE
Ubuntu 22:04 - No context menu

### ISSUE THREAD

**Issue by jeranio** [rabbitvcs/rabbitvcs#348]
Hello,
I have tried several recommendations but nothing seems to bring up the context menu.

**Distro**
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

**PC**
product: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
version: 6.158.10
size: 3987MHz
capacity: 4100MHz
width: 64 bits

**Comment by Forage** [comment]
Working here.
Do you have the rabbitvcs-nautilus package insalled?
Which version of rabbitvcs are you running?
How did you install it?

**Comment by CBtiger** [comment]
I am using Xubuntu 22.04 on 64bit with Nemo FM and RabbitVCS 0.18, Pysvn 1.9.15.2070, ConfigObj 5.0.6. As it was removed from the repository, I installed it manually using files from the Debian repo. 

I used it before in 18.04 and it worked fine. 
After moving to 22.04 I noted that the context menu does appear but without any RabbitVCS items. Also the FM/Edit menu does not contain them. It behaves like when clicking a folder that is not under version control. 
However, after clicking the same folder a second time. 90% of the cases the RabbitVCS context menu items appear normally. In the remaining 10% entering the folder and clicking a file then back an forth usually does the trick. 

Its a bit tedius but fortunately not too bad to work normally with it.

**Comment by ianhgenesys** [comment]
I am using VirtualBox 7 to install Ubuntu 22.04 LTS and used sudo apt-get install rabbitvcs* to install RabbitVCS. Everything installs but I am not getting the context menu. Upon running nautilus in the terminal, I get this error:

`ianh@UbuntuJammy:~$ nautilus

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 52, in <module>

    from gi.repository import GObject

ModuleNotFoundError: No module named 'gi'

ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Error.ServiceUnknown: The name org.google.code.rabbitvcs.RabbitVCS.Checker was not provided by any .service files

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner

    return self.get_name_owner(bus_name)

  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner

    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,

  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking

    reply_message = self.send_message_with_reply_and_block(

dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.google.code.rabbitvcs.RabbitVCS.Checker': no such name



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 267, in _connect_to_checker

    self.status_checker = self.session_bus.get_object(SERVICE,

  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object

    return self.ProxyObjectClass(self, bus_name, object_path,

  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__

    self._named_service = conn.activate_name_owner(bus_name)

  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner

    self.start_service_by_name(bus_name)

  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name

    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,

  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking

    reply_message = self.send_message_with_reply_and_block(

dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.google.code.rabbitvcs.RabbitVCS.Checker was not provided by any .service files

Traceback (most recent call last):

  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 210, in __init__

    self.status_checker.assert_version(EXT_VERSION)

  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 285, in assert_version

    pid = self.status_checker.CheckVersionOrDie(version)

AttributeError: 'NoneType' object has no attribute 'CheckVersionOrDie'

sys:1: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.793: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.794: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.794: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.794: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.794: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.794: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed



** (org.gnome.Nautilus:24506): CRITICAL **: 08:40:11.794: nautilus_info_provider_update_file_info: assertion 'NAUTILUS_IS_INFO_PROVIDER (self)' failed`

Looking at usr/lib/python3/dist-packages/, I can see a gi folder inside. What could be the issue here?

**Comment by philippun1** [comment]
Cannot reproduce. I also installed rabbitvcs* 0.18-3 in Ubuntu 22.04 in a VirtualBox 7 VM. Everything works as expected. Can you maybe check if python3-gi is installed properly? Eventually reinstall it with: `sudo apt install --reinstall python3-gi`

**Comment by ianhgenesys** [comment]
Thanks for the reply. I uninstalled VirtualBox and Ubuntu 22.04 from my computer and reinstalled them. The first thing I did was allow sudo permissions followed by installing rabbitvcs and it now works. Have no idea why the previous tries didnt work??

**Comment by philippun1** [comment]
rabbitvcs does work with python 3.11 i.e. in Ubuntu 23.04, so I assume something got messed up with the python 3.11 installation. How did you install it?

**Comment by ianhgenesys** [comment]
I downloaded the [XZ compressed source tarball](https://www.python.org/ftp/python/3.11.3/Python-3.11.3.tar.xz) from their site and followed the README to install it. Does this mean I need to upgrade to Ubuntu 23.04 to make it work?

**Comment by philippun1** [comment]
No, but you either have to stick with the default python, or make it work with your custom python version manually. What is the exact error?

**Comment by ianhgenesys** [comment]
When I type nautilus into the console, this error appears:
ianh@Jammy:~$ nautilus
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 52, in <module>
    from gi.repository import GObject
ModuleNotFoundError: No module named 'gi'
ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Error.ServiceUnknown: The name org.google.code.rabbitvcs.RabbitVCS.Checker was not provided by any .service files
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.google.code.rabbitvcs.RabbitVCS.Checker': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 267, in _connect_to_checker
    self.status_checker = self.session_bus.get_object(SERVICE,
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.google.code.rabbitvcs.RabbitVCS.Checker was not provided by any .service files
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 210, in __init__
    self.status_checker.assert_version(EXT_VERSION)
  File "/usr/lib/python3/dist-packages/rabbitvcs/services/checkerservice.py", line 285, in assert_version
    pid = self.status_checker.CheckVersionOrDie(version)
AttributeError: 'NoneType' object has no attribute 'CheckVersionOrDie'
Nautilus-Share-Message: 10:01:46.540: Called "net usershare info" but it failed: Failed to execute child process “net” (No such file or directory)

**Comment by philippun1** [comment]
The python3-gi package is for the builtin python. Does `python -m pip install PyGObject` help?
