### ISSUE TITLE
SyntaxError: from __future__ imports must occur at the beginning of the file

### ISSUE THREAD

**Issue by GrantEdwards** [rabbitvcs/rabbitvcs#351]
I just cloned the git repo at dfb30375e8de076027d985b928ec081f5116972a, did `python setup.py install --user` with Python 3.9, and when I try to start a browser I get this:

~~~
$ rabbitvcs browser
/home/grante/.local/lib/python3.9/site-packages/rabbitvcs-0.18-py3.9.egg/rabbitvcs/ui/__init__.py:31: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib
Traceback (most recent call last):
  File "/home/grante/.local/lib/python3.9/site-packages/rabbitvcs-0.18-py3.9.egg/rabbitvcs/ui/browser.py", line 8, in <module>
    import rabbitvcs.ui.action
  File "/home/grante/.local/lib/python3.9/site-packages/rabbitvcs-0.18-py3.9.egg/rabbitvcs/ui/action.py", line 36
    from __future__ import absolute_import
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
~~~

Moving that import to the top of ui/action.py seems to fix it.

**Comment by GrantEdwards** [comment]
The same problem exists in other files (e.g. ui/log.py).

**Comment by CloCkWeRX** [comment]
Pushed fixes for those, my bad; was futzing about with trying to get a CI pipeline / modernised tools in place; then got distracted for a while.

It's been... a long time... since I had my head in the python landscape; so PRs welcome around improving this.

**Comment by yochananmarqos** [comment]
It looks like the plugins need the same treatment. Using the latest commit (b88b384) launching Nautilus:

```
VERS: sys.version_info(major=3, minor=10, micro=5, releaselevel='final', serial=0)
  File "/usr/share/nautilus-python/extensions/RabbitVCS.py", line 59
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
```
