### ISSUE TITLE
No Context Menu + Thunar segfault

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [rabbitvcs/rabbitvcs#366]
Hello,
I'm on Ubuntu Kinetic x64, Mate Desktop.
I saw in this [issue #384 post ](https://github.com/rabbitvcs/rabbitvcs/issues/348) a suggestion to install the rabbitvcs-nautilus package. This package does not exist in Ubuntu Kinetic.

So I tried Thunar & the rabbitvcs-thunar plugin. It segfaults with below message, probably missing a standard XFCE library?
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Thunarx not available
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 136, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Thunarx, introspection typelib not found

(thunar:489327): thunarx-python-WARNING **: 10:00:07.110: thunarx_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/thunarx-python/extensions/RabbitVCS.py", line 41, in <module>
    from gi.repository import GObject, Gtk, Thunarx
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 136, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Thunarx, introspection typelib not found
Segmentation fault
```

**P.S.** Perhaps it would also be useful to specify on the [Known Issues](http://wiki.rabbitvcs.org/wiki/support/known-issues) page to state that plugins (rabbitvcs-thunar, etc) should also be installed?

**Comment by philippun1** [comment]
Installing `gir1.2-thunarx-3.0` fixed the problem for me on Ubuntu MATE 23.10.
Closing this since Ubuntu Kinetic will be EOL very soon.
