### ISSUE TITLE
Defaulting to the "dummy" driver after update

### ISSUE THREAD

**Issue by Queuecumber** [rabbitvcs/rabbitvcs#49]
Ubuntu 14.04 using Gnome 3.12

When I'm not in a repository I see the menu options for cloning.

When I'm a repository none of the context menus show up.

Icons don't show at all.

Examining the terminal output from nautilus gives the following errors:

```
ERROR   rabbitvcs.services.checkerservice       org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
retval = candidate_method(self, *args, **keywords)
File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
path_dict = self.status_checker.generate_menu_conditions(upaths)
File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 55, in generate_menu_conditions
conditions = MainContextMenuConditions(self.vcs_client, paths)
File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1207, in __init__
self.generate_statuses(paths)
File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1217, in generate_statuses
statuses_tmp = self.vcs_client.statuses(path)
File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 210, in statuses
client = self.client(path)
File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 189, in client
return self.git(guess["repo_path"], is_repo_path=False)
File "/usr/local/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 117, in git
repo_path = git.find_repository_path(path)
AttributeError: Dummy instance has no attribute 'find_repository_path'
None
```

**Comment by sysoncloud** [comment]
I ran into this same problem on my Ubuntu 14.04, the folder and context menu icon shows normal,
after installed this plugin, the Nautilus occupy much CPU.

2017-05-24 09:33:58,489 ERROR   rabbitvcs.services.checkerservice       org.free
desktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message
_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/pymodules/python2.7/rabbitvcs/services/checkerservice.py", line
 185, in GenerateMenuConditions
    path_dict = self.status_checker.generate_menu_conditions(upaths)
  File "/usr/lib/pymodules/python2.7/rabbitvcs/services/statuschecker.py", line 
55, in generate_menu_conditions
    conditions = MainContextMenuConditions(self.vcs_client, paths)
  File "/usr/lib/pymodules/python2.7/rabbitvcs/util/contextmenu.py", line 1207, 
in __init__
    self.generate_statuses(paths)
  File "/usr/lib/pymodules/python2.7/rabbitvcs/util/contextmenu.py", line 1217, 
in generate_statuses
    statuses_tmp = self.vcs_client.statuses(path)
  File "/usr/lib/pymodules/python2.7/rabbitvcs/vcs/__init__.py", line 210, in st
atuses
    client = self.client(path)
  File "/usr/lib/pymodules/python2.7/rabbitvcs/vcs/__init__.py", line 189, in client:
    return self.git(guess["repo_path"], is_repo_path=False)
  File "/usr/lib/pymodules/python2.7/rabbitvcs/vcs/__init__.py", line 117, in git
    repo_path = git.find_repository_path(path)
AttributeError: Dummy instance has no attribute 'find_repository_path'
None
......

**Comment by adamplumb** [comment]
This should be fixed in master now.
