### ISSUE TITLE
Git intgeration in Nemo doesn't work

### ISSUE THREAD

**Issue by Dave1704** [rabbitvcs/rabbitvcs#79]
Hi everbody,

I'm having problems with RabbitVCS and git under mint with Cinnamon and Nemo.
I'm posting this here since to me it looks more like a problem in RabbitVCS itself than the integration.
But I'm not sure about it.

The concrete problem is, that I'm not able to use RabbitVCS on git repositories
and that just bombs are shown as labels for all the files and folders.

If wasn't able to find the problem in the issue tracker but it looked very similar to an older one
I found [here](https://groups.google.com/forum/#!msg/rabbitvcs-activity/98twyDzrEQM/ksMM2Ven-uwJ).

My rabbitvcs-core package is version 0.15.2-1 if that helps.
Please feel free to ask me for more information.

This is what I found in the log and what seems to produce the problem:
```
2015-02-10 21:25:30,508 ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
    path_dict = self.status_checker.generate_menu_conditions(upaths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 55, in generate_menu_conditions
    conditions = MainContextMenuConditions(self.vcs_client, paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1193, in __init__
    self.generate_statuses(paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1203, in generate_statuses
    statuses_tmp = self.vcs_client.statuses(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 183, in statuses
    return client.statuses(path, recurse=recurse, invalidate=invalidate)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/__init__.py", line 173, in statuses
    gittyup_statuses = self.client.status(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1356, in status
    return self.status_porcelain(path)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 1211, in status_porcelain
    ignored_path=components.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
None
```

**Comment by Dave1704** [comment]
Since nobody of you seems to care about this, I cared about it for myself and for everyone else reading this in the future.

The problem is that client.py checks explicitly for the string "Would remove <filename>".
But since I'm runnign my machine on german the actual string is "Würde <filename> löschen".

I fixed it by instead checking for the german version with "^(Würde)\s(.*?)\s(löschen)$". But that isn't a real solution.
At least for "determine the ignored files and directories in Repo" there is a clean solution provided by git: http://git-scm.com/docs/git-check-ignore
It just prints the names of the files and nothing else.

But I wasn't able to find such a thing for "determine untracked directories".

However, I would still appreciate a clean solution for this!

**Comment by Dave1704** [comment]
I laready tried implementing the clean solution I proposed before. Even though I get a perfect output on the console for `git check-ignore * /path/to/repo` but if I set cmd to `["git", "check-ignore", "*", self.repo.path]` I get an empty result. Does someone know the reason for that? Just to mention it, I don#t have any experience with python.

**Comment by tillwo** [comment]
Hi Dave1704!

I am suffering from the same bug. I use RabbitVCS 0.15.2-1 with Ubuntu 14.04.2. Thank you for documenting and analyzing the bug!

Being totally new to Python myself, too, I tried a different approach to fix the issue. The error occurs because RabbitVCS parses the text output of `git` and fails because the output is localized in German in our case. Now my approach is to switch off the German localization so that the text parser sees the "Would remove" string it expects instead of "Würde löschen".

Digging through the source code, I found that `git` is eventually called via `subprocess.Popen()` from `command.py` (line 43 in my case). I added another parameter which sets the environment variable `LANG=C` which results in English localization:

```
--- command.py.org	2015-04-16 15:13:26.907517924 +0200
+++ command.py	2015-04-16 15:14:40.743520410 +0200
@@ -47,7 +47,8 @@
                                 stdout=subprocess.PIPE,
                                 close_fds=True,
                                 preexec_fn=os.setsid,
-                                universal_newlines=True)
+                                universal_newlines=True,
+                                env={'LANG':'C'})
 
         stdout = []
```

With this patch applied, RabbitVCS works again and I see green check marks instead of grey bomb icons. :-)

Maybe somebody with more experience in Python and/or GIT than me can comment on whether this is done the right way. Problems may arise because my "hack" simply *replaces* the entire environment instead of adding (or replacing) LANG.

From https://docs.python.org/2/library/subprocess.html:
> If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of inheriting the current process’ environment, which is the default behavior.
>
> Note: If specified, env must provide any variables required for the program to execute. On Windows, in order to run a side-by-side assembly the specified env must include a valid SystemRoot.

**Comment by Dave1704** [comment]
Hi tillwo,

it's great to hear that others put effort into it as well :-)
Maybe we can get this to become a pullrequest. But it would be better to keep the rest of the environment. I think that should be possible even though I don#t know how at the moment.

**Comment by CloCkWeRX** [comment]
Feel free to turn this into a pull request
