### ISSUE TITLE
Menu does not appear in Nemo under Linux Mint or menu appears incomplete

### ISSUE THREAD

**Issue by bulkware** [rabbitvcs/rabbitvcs#80]
I get the error in the logs (multiple times):

2015-02-16 08:43:12,217 ERROR	rabbitvcs.services.checkerservice	org.freedesktop.DBus.Python.pysvn._pysvn_2_7.ClientError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/services/statuschecker.py", line 55, in generate_menu_conditions
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 1194, in __init__
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/util/contextmenu.py", line 637, in generate_path_dict
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/__init__.py", line 200, in is_versioned
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 347, in is_versioned
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 277, in client_info
ClientError: '/home/apm/projects/project/project_trunk' is not a working copy
None

With the debug on, I get this (multiple times):
2015-02-16 09:14:37,191 DEBUG	rabbitvcs.services.service	Started process: 3440
2015-02-16 09:14:37,255 DEBUG	rabbitvcs.services.checkerservice:main	Checker: starting service: /org/google/code/rabbitvcs/StatusChecker (3440)
2015-02-16 09:16:07,496 DEBUG	rabbitvcs.vcs.svn	Exception occured in SVN.status() for /home/username/projects/project
2015-02-16 09:16:07,496 DEBUG	rabbitvcs.vcs.svn	Exception occured in SVN.status() for /home/username/projects/project
2015-02-16 09:16:07,496 ERROR	rabbitvcs.vcs.svn	Can't open directory '/home/username/projects/project/...': Too many open files
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 254, in statuses
ClientError: Can't open directory '/home/username/projects/project/...': Too many open files
2015-02-16 09:16:07,496 ERROR	rabbitvcs.vcs.svn	Can't open directory '/home/username/projects/project/...': Too many open files
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 254, in statuses
ClientError: Can't open directory '/home/username/projects/project/...': Too many open files
2015-02-16 09:16:07,497 DEBUG	rabbitvcs.vcs.svn	Exception occured in SVN.status() for /home/username/projects/project
2015-02-16 09:16:07,497 DEBUG	rabbitvcs.vcs.svn	Exception occured in SVN.status() for /home/username/projects/project
2015-02-16 09:16:07,498 ERROR	rabbitvcs.vcs.svn	'/home/username/projects/project' is not a working copy
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 254, in statuses
ClientError: '/home/username/projects/project' is not a working copy
2015-02-16 09:16:07,498 ERROR	rabbitvcs.vcs.svn	'/home/username/projects/project' is not a working copy
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/svn/__init__.py", line 254, in statuses
ClientError: '/home/username/projects/project' is not a working copy
2015-02-16 09:16:07,498 DEBUG	rabbitvcs.vcs.svn	Exception occured in SVN.status() for /home/username/projects/project
2015-02-16 09:16:07,498 DEBUG	rabbitvcs.vcs.svn	Exception occured in SVN.status() for /home/username/projects/project
2015-02-16 09:16:07,499 ERROR	rabbitvcs.vcs.svn	'/home/username/projects/project' is not a working copy

Versions:
Kernel: 3.13.0-37-generic x86_64 (64 bit)
Desktop: Gnome
Distro: Linux Mint 17.1 Rebecca
nemo: 2.4.5
Python - 2.7.6
RabbitVCS - 0.15.2
Subversion - 1.8.8.
Pysvn - 1.7.8.0
ConfigObj - 4.7.2

Language:
en_US.UTF-8

I am happy to provide more information about this problem. Just tell me how I can help.

**Comment by bulkware** [comment]
Screenshot of the menu:
![svn](https://cloud.githubusercontent.com/assets/3463048/6224336/dce4cd88-b682-11e4-9fbd-0168f9dd866d.png)

**Comment by bulkware** [comment]
I updated to the latest version 1.16.0. Now my versions are:

RabbitVCS - 0.16.0
Subversion - 1.8.8.
Pysvn - 1.7.8.0
ConfigObj - 4.7.2

The issue still remains. My menu selections are incomplete. When I want to update something, I have to do it using rabbitvcs-cli.

**Comment by CloCkWeRX** [comment]
#57

**Comment by CloCkWeRX** [comment]
```ClientError: '/home/apm/projects/project/project_trunk' is not a working copy``` that you are trying to view a non repository, or a repo that rabbitvcs can't recognize. Safe to ignore.

... simply suggests that's what is happening.

As for the too many files; see http://stackoverflow.com/questions/18280612/ioerror-errno-24-too-many-open-files - I suspect that's something related more to debug mode and not closing file handles; as the errors should have occurred in the earlier error.

**Comment by CloCkWeRX** [comment]
Too many files is probably #76

**Comment by bulkware** [comment]
I think the problem with these incomplete menus is because RabbitVCS does not recognise repos correctly. The same repos I checkout using RabbitVCS.

...but I do understand that these log messages are from different problems. I don't know how to provide more information about this issue. I read the docs and set the debug mode and these messages I get. If you can tell me how to get more detailed information about this issue, please do. I'll be happy to help =)

...or does this menu issue belong to the nemo plugin, not here?

**Comment by ninazu** [comment]
a)Check permissions for:
~/.config/rabbitvcs

b)Try.

1.Go to Nemo->Edit->Plugins->Extensions. 
2.Disable plugin
3.Restart nemo
4.Enable plugin
5.Restart nemo


Work for me.

**Comment by bulkware** [comment]
Thank you ninazu for your answer. Directory and file permissions were set for my user and the method b had no effect. Is there something else I should check or try?
