### ISSUE TITLE
No module named contextmenu Fedora 21 64b

### ISSUE THREAD

**Issue by Pepan** [rabbitvcs/rabbitvcs#96]
Hi.
after installation by
yum install python-simplejson
yum install rabbitvcs-core
yum install rabbitvcs-cli
yum install rabbitvcs-gedit
yum install rabbitvcs-nautilus

and also
ln -s /usr/lib64/libpython2.7.so /usr/lib/libpython2.7.so

I still did not see any context menu. 
![no context menu](https://cloud.githubusercontent.com/assets/714872/7201413/10627360-e507-11e4-9832-276f9930b6f2.png)

Also check icon is only on one project folder but others are under version control too (subversion or git)
![alone check icon](https://cloud.githubusercontent.com/assets/714872/7201411/ffcd6898-e506-11e4-9aa5-169594f39f8f.png)

this is from : journalctl -b -p warning

dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: ImportError: No module named contextmenu
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: None
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: ERROR        rabbitvcs.services.checkerservice        org.freedesktop.DBus.Python.ImportError: Traceback (most recent call last):
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: File "/usr/lib64/python2.7/site-packages/dbus/service.py", line 826, in _message_cb
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: retval = candidate_method(self, *args, **keywords)
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: File "/usr/lib/python2.7/site-packages/rabbitvcs/services/checkerservice.py", line 185, in GenerateMenuConditions
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: path_dict = self.status_checker.generate_menu_conditions(upaths)
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: File "/usr/lib/python2.7/site-packages/rabbitvcs/services/statuschecker.py", line 53, in generate_menu_conditions
dub 17 13:51:32 jch-jchsoft-cz org.gnome.Nautilus[1985]: from rabbitvcs.util.contextmenu import MainContextMenuConditions

**Comment by Pepan** [comment]
Huh after some time and system restart it works nearly as expected.
